name: Build
on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:


jobs:
    build-linux:
        uses: IRFM/librir/.github/workflows/build-linux.yml@dubusster-patch-2
        
    build-windows:
        uses: IRFM/librir/.github/workflows/build-windows.yml@dubusster-patch-2
      